#!/bin/bash

echo "COMPOSE_CONVERT_WINDOWS_PATHS=1"
echo "COMPOSE_PROJECT_NAME=linkeddatahub"
echo "PROTOCOL=https"
echo "PROXY_HTTP_PORT=81"
echo "PROXY_HTTPS_PORT=4443"
echo "HOST=localhost"
echo "ABS_PATH=/"
echo "OWNER_MBOX=test@linkeddatahub.com"
echo "OWNER_GIVEN_NAME=Test"
echo "OWNER_FAMILY_NAME=Agent"
echo "OWNER_ORG_UNIT=LinkedDataHub (localhost)"
echo "OWNER_ORGANIZATION=AtomGraph"
echo "OWNER_LOCALITY=Copenhagen"
echo "OWNER_STATE_OR_PROVINCE=Denmark"
echo "OWNER_COUNTRY_NAME=DK"
echo "OWNER_KEY_PASSWORD=changeit"