language: c

env:
  - ASF_ARCHIVE=http://archive.apache.org/dist/ JENA_VERSION=3.13.1

before_install:
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - find ./http-tests -name "*.sh" -exec chmod +x {} \;
  - curl -sS --fail "${ASF_ARCHIVE}jena/binaries/apache-jena-${JENA_VERSION}.tar.gz" -o jena.tar.gz
  - tar zxf jena.tar.gz 
  - mv apache-jena* /jena 
  - rm jena.tar.gz* 
  - cd /jena 
  - rm -rf *javadoc* *src* bat
  - ls /jena -l
  - export JENA_HOME=/jena
  - export PATH="$PATH:$JENA_HOME/bin"
  - ls $JENA_HOME -l

install:
  - bash ./http-tests/print-env-file.sh > .env
  - ls -la
  - docker-compose pull
  - docker-compose up -d # run in the background
  - cd http-tests

before_script:
  - while ! curl -w "%{http_code}\n" -k -s https://localhost:4443/ | grep "200" ; do sleep 1 ; done # wait for the webapp to start

script:
  - bash ./run.sh changeit # run tests with owner password

after_script:
  - docker-compose down
  - docker-compose rm -f

notifications:
  email:
    recipients:
      - martynas@atomgraph.com