language: c

services:
  - docker

env:
  - ASF_ARCHIVE=http://archive.apache.org/dist/ JENA_VERSION=3.13.1 JENA_HOME="${TRAVIS_BUILD_DIR}/apache-jena-${JENA_VERSION}" PATH="$PATH:$JENA_HOME/bin" BASE_URI=https://localhost:4443/ OWNER_CERT_PWD=changeit SECRETARY_CERT_PWD=LinkedDataHub

before_install:
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - find ./http-tests -name "*.sh" -exec chmod +x {} \;
  - curl -sS --fail "${ASF_ARCHIVE}jena/binaries/apache-jena-${JENA_VERSION}.tar.gz" -o jena.tar.gz
  - tar zxf jena.tar.gz 
  - docker build -t atomgraph/linkeddatahub .

install:
  - ./http-tests/print-env-file.sh > .env
  - docker-compose up -d # run in the background

before_script:
  - while ! curl -w "%{http_code}\n" -k -s "${BASE_URI}" | grep "200" ; do sleep 1 ; done # wait for the webapp to start
  - openssl pkcs12 -in ./certs/owner.p12 -out ./http-tests/owner.p12.pem -passin pass:"$OWNER_CERT_PWD" -passout pass:"$OWNER_CERT_PWD" # re-generate the owner PEM cert - seems to differ with different openssl versions?
  - openssl pkcs12 -in ./certs/secretary.p12 -out ./http-tests/secretary.p12.pem -passin pass:"$SECRETARY_CERT_PWD" -passout pass:"$SECRETARY_CERT_PWD" # re-generate the secretary PEM cert - seems to differ with different openssl versions?
  - pushd .
  - cd http-tests

script:
  - ./run.sh "$PWD/owner.p12.pem" "$OWNER_CERT_PWD" "$PWD/secretary.p12.pem" "$SECRETARY_CERT_PWD" # run tests

after_script:
  - popd
  - docker-compose down
  - docker-compose rm -f

notifications:
  email:
    recipients:
      - martynas@atomgraph.com