#!/usr/bin/env bash
set -euo pipefail

initialize_dataset "$END_USER_BASE_URL" "$TMP_END_USER_DATASET" "$END_USER_ENDPOINT_URL"
initialize_dataset "$ADMIN_BASE_URL" "$TMP_ADMIN_DATASET" "$ADMIN_ENDPOINT_URL"
purge_cache "$END_USER_VARNISH_SERVICE"
purge_cache "$ADMIN_VARNISH_SERVICE"
purge_cache "$FRONTEND_VARNISH_SERVICE"
reset_packages
clear_ontology

# Test: declarative package install — a single ldh:import triple PATCHed into the dataspace
# settings composes the package stylesheet into the app stylesheet on the next request.
# The update strings mirror the ones generated by the settings modal's package Save button.

app_uri="urn:linkeddatahub:apps/end-user"
package_uri="https://packages.linkeddatahub.com/editor/taxonomy/#this"

slug="taxonomy-package-probe"
doc="${END_USER_BASE_URL}${slug}/"
concept="${doc}#this"

# The package's rule is that the SKOS hierarchy predicates render as the concept tree rather than
# as statement rows: it binds skos:narrower/broader/related/member to an empty ac:PropertyEditor
# template. So what the import moves is the concept's skos:broader ROW.
#
# It does not move the statement, and the difference is the whole reason this test reads the markup
# with XPath instead of grepping it for the object URI. Since a document's markup asserts the graph
# the same URL serves, every triple also gets an RDFa carrier - a link or meta element that renders
# nothing - and ac:PropertyEditor does not reach those, nor should it: what a document serves as RDF
# cannot change because a package chooses to draw it differently. The object URI is therefore in the
# markup in every phase, and a grep for it passes in both directions.
#
# The concept is a resource of its own that the document describes, not the document itself. A
# dh:Item carrying skos:broader directly renders nothing: the property list belongs to the described
# resource, so with no foaf:primaryTopic there is nothing for ac:PropertyEditor to emit and the
# assertion would pass in both directions for a second reason.
broader="http://www.w3.org/2004/02/skos/core#broader"
marker="http://example.org/skos-broader-probe"

# XHTML rather than text/html, as in rdfa/graph-in-markup.sh: the same rendering is then well-formed
# and can be counted with XPath instead of matched as text. Attribute order is a serialization
# detail and nothing here depends on it.

function document()
{
  curl -k -s \
    -H "Accept: application/xhtml+xml" \
    -H "Accept-Language: en" \
    -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
    "$doc"
}

# Counts the two kinds of element that can carry the marker, from one fetch. Sets:
#   ROWS     - the rendered property row, which the import suppresses
#   CARRIERS - the RDFa carrier, which asserts the statement whatever the import does
#
# The body is read into a variable first: `xmllint -` consumes all of it, and with `set -o pipefail`
# a reader that stopped early would SIGPIPE curl and fail the whole pipeline. That only happens when
# curl is still writing at the moment the reader exits, which made this test fail randomly.
function probe()
{
  local body
  body=$(document)
  ROWS=$(xmllint --xpath "count(//*[@property = '$broader'][@resource = '$marker'][local-name() != 'link'])" - <<< "$body" 2> /dev/null || echo "ERR")
  CARRIERS=$(xmllint --xpath "count(//*[local-name() = 'link'][@property = '$broader'][@resource = '$marker'])" - <<< "$body" 2> /dev/null || echo "ERR")
}

# assert the row count for a phase, and that the carrier is there whatever the row does
function assert_rows()
{
  local phase="$1" expected="$2" note="$3"
  probe
  echo "DEBUG: [$phase] Expected rows: $expected  Got: $ROWS  (carriers: $CARRIERS, expected >= 1)"
  if [ "$ROWS" != "$expected" ]; then
    echo "DEBUG: [$phase] $note" >&2
    exit 1
  fi
  if [ "$CARRIERS" = "ERR" ] || [ "$CARRIERS" -lt 1 ]; then
    echo "DEBUG: [$phase] the statement lost its RDFa carrier - the markup no longer asserts the graph the document serves" >&2
    exit 1
  fi
}

function patch_settings()
{
  curl -k -w "%{http_code}" -o /dev/null -s \
    -X PATCH \
    -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
    -H "Content-Type: application/sparql-update" \
    -d "$1" \
    "${END_USER_BASE_URL}settings"
}

# The settings live in the in-memory application model, which initialize_dataset does not
# reset - an import left behind by a failed assertion would stay for the rest of the suite.

function remove_import()
{
  patch_settings "DELETE { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }" > /dev/null || true
}

trap remove_import EXIT

# a document describing a SKOS concept that has a broader concept

curl -k -w "%{http_code}\n" -o /dev/null -f -s \
  -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
  -X PUT \
  -H "Content-Type: application/n-triples" \
  --data-binary @- \
  "$doc" <<EOF \
| grep -q "$STATUS_CREATED"
<${doc}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/ns/ldt/document-hierarchy#Item> .
<${doc}> <http://purl.org/dc/terms/title> "Taxonomy editor package probe" .
<${doc}> <http://rdfs.org/sioc/ns#has_container> <${END_USER_BASE_URL}> .
<${doc}> <http://xmlns.com/foaf/0.1/primaryTopic> <${concept}> .
<${concept}> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
<${concept}> <http://www.w3.org/2004/02/skos/core#prefLabel> "Probe concept" .
<${concept}> <http://www.w3.org/2004/02/skos/core#broader> <${marker}> .
EOF

# without the package, the broader statement renders as a property row

assert_rows "before import" 1 "broader row missing before import - the fixture does not exercise the package rule"

# declare the package import

status=$(patch_settings "INSERT { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }")

if [[ ! "$status" =~ ^($STATUS_NO_CONTENT)$ ]]; then
  echo "DEBUG: Expected: $STATUS_NO_CONTENT  Got: $status" >&2
  exit 1
fi

# the package suppresses the row — on the very next request, no restart and no sleep

assert_rows "after import" 0 "broader row still rendered after import - the package stylesheet did not compose"

# remove the package import

status=$(patch_settings "DELETE { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }")

if [[ ! "$status" =~ ^($STATUS_NO_CONTENT)$ ]]; then
  echo "DEBUG: Expected: $STATUS_NO_CONTENT  Got: $status" >&2
  exit 1
fi

# and the row is back

assert_rows "after removal" 1 "broader row still suppressed after the import was removed"
