#!/usr/bin/env bash
set -euo pipefail

initialize_dataset "$END_USER_BASE_URL" "$TMP_END_USER_DATASET" "$END_USER_ENDPOINT_URL"
initialize_dataset "$ADMIN_BASE_URL" "$TMP_ADMIN_DATASET" "$ADMIN_ENDPOINT_URL"
purge_cache "$END_USER_VARNISH_SERVICE"
purge_cache "$ADMIN_VARNISH_SERVICE"
purge_cache "$FRONTEND_VARNISH_SERVICE"

# Test: declarative package install — a single ldh:import triple PATCHed into the dataspace
# settings composes the package stylesheet into the app stylesheet on the next request.
# The update strings mirror the ones generated by the settings modal's package Save button.

app_uri="urn:linkeddatahub:apps/end-user"
package_uri="https://packages.linkeddatahub.com/skos/#this"

# stylesheet marker injected into every page by the SKOS package layout.xsl
marker="com/linkeddatahub/demo/skos/css/bootstrap.css"

# The rendered homepage is tens of KiB and the marker sits in <head>, within its first
# 2 KiB. Assertions therefore read the response from a here-string rather than piping
# curl into `grep -q`: `grep -q` closes the pipe on its first match, and with
# `set -o pipefail` the SIGPIPE'd curl fails the whole pipeline. That only happens when
# curl is still writing at the moment grep exits, which made this test fail randomly.

function homepage()
{
  curl -k -s \
    -H "Accept: text/html" \
    -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
    "$END_USER_BASE_URL"
}

function patch_settings()
{
  curl -k -w "%{http_code}" -o /dev/null -s \
    -X PATCH \
    -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
    -H "Content-Type: application/sparql-update" \
    -d "$1" \
    "${END_USER_BASE_URL}settings"
}

function import_triple_count()
{
  curl -k -s \
    -E "$OWNER_CERT_FILE":"$OWNER_CERT_PWD" \
    -H "Accept: application/n-triples" \
    "${END_USER_BASE_URL}settings" \
  | grep -c "linkeddatahub#import" || true
}

# The settings live in the in-memory application model, which initialize_dataset does not
# reset - an import left behind by a failed assertion would stay for the rest of the suite.

function remove_import()
{
  patch_settings "DELETE { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }" > /dev/null || true
}

trap remove_import EXIT

# verify the homepage is not rendered with the package stylesheet initially
response=$(homepage)

if grep -qF "$marker" <<< "$response"; then
  echo "DEBUG: package stylesheet marker present before import"
  exit 1
fi

# declare the package import
status=$(patch_settings "INSERT { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }")

if [[ ! "$status" =~ ^($STATUS_NO_CONTENT)$ ]]; then
  echo "DEBUG: Expected $STATUS_NO_CONTENT from the INSERT PATCH, got: $status"
  exit 1
fi

# verify the homepage is rendered with the package stylesheet — no restart, no sleep
response=$(homepage)

if ! grep -qF "$marker" <<< "$response"; then
  echo "DEBUG: package stylesheet marker missing after import"
  echo "DEBUG: Expected marker: $marker"
  echo "DEBUG: Response size: $(wc -c <<< "$response") bytes"
  echo "DEBUG: ldh:import triple count in settings = $(import_triple_count)"
  exit 1
fi

# remove the package import
status=$(patch_settings "DELETE { <${app_uri}> <https://w3id.org/atomgraph/linkeddatahub#import> <${package_uri}> . } WHERE { }")

if [[ ! "$status" =~ ^($STATUS_NO_CONTENT)$ ]]; then
  echo "DEBUG: Expected $STATUS_NO_CONTENT from the DELETE PATCH, got: $status"
  exit 1
fi

# verify the homepage is no longer rendered with the package stylesheet
response=$(homepage)

if grep -qF "$marker" <<< "$response"; then
  echo "DEBUG: package stylesheet marker still present after removal"
  echo "DEBUG: ldh:import triple count in settings = $(import_triple_count)"
  exit 1
fi
