PREFIX :     <ns/domain#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:  <http://purl.org/dc/terms/>

CONSTRUCT
{
    ?this skos:hasTopConcept [ a :Concept ] ;
        dct:title [ a xsd:string ] .
}
WHERE {}