PREFIX :     <ns/domain#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT
{
    ?this skos:inScheme [ a :ConceptScheme ] ;
        skos:topConceptOf [ a :ConceptScheme ] ;
        skos:prefLabel [ a xsd:string ] ;
        skos:altLabel [ a xsd:string ] ;
        skos:hiddenLabel [ a xsd:string ] ;
        skos:notation [ a xsd:string ] ;
        skos:note [ a xsd:string ] ;
        skos:changeNote [ a xsd:string ] ;
        skos:definition [ a xsd:string ] ;
        skos:editorialNote [ a xsd:string ] ;
        skos:example [ a xsd:string ] ;
        skos:historyNote [ a xsd:string ] ;
        skos:scopeNote [ a xsd:string ] ;
        skos:semanticRelation [ a :Concept ] ;
        skos:broader [ a :Concept ] ;
        skos:narrower [ a :Concept ] ;
        skos:related [ a :Concept ] ;
        skos:broaderTransitive [ a :Concept ] ;
        skos:narrowerTransitive [ a :Concept ] ;
        skos:mappingRelation [ a :Concept ] ;
        skos:broadMatch [ a :Concept ] ;
        skos:narrowMatch [ a :Concept ] ;
        skos:relatedMatch [ a :Concept ] ;
        skos:exactMatch [ a :Concept ] ;
        skos:closeMatch [ a :Concept ] .
}
WHERE {}