PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
PREFIX a:       <https://w3id.org/atomgraph/core#>
PREFIX lds:     <https://w3id.org/atomgraph/linkeddatahub/dataspaces#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>

SELECT ?app ?type ?origin ?quadStore ?graphStore ?endpoint ?authUser ?authPwd ?authToken ?maker
{
    GRAPH ?appGraph
    {
        ?app a ?type ;
            lds:origin ?origin ;
            lds:service ?service .
        FILTER(?type IN (lds:EndUserDataspace, lds:AdminDataspace))
        OPTIONAL { ?app foaf:maker ?maker }

        GRAPH ?serviceGraph
        {
            ?service sd:endpoint ?endpoint .
            OPTIONAL { ?service a:quadStore ?quadStore }
            OPTIONAL { ?service a:graphStore ?graphStore }
            OPTIONAL
            {
                ?service a:authUser ?authUser ;
                    a:authPwd ?authPwd .
            }
            OPTIONAL { ?service a:authToken ?authToken }
        }
    }
}
