/**
 *  Copyright 2019 Martynas Jusevičius <martynas@atomgraph.com>
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
package com.atomgraph.linkeddatahub.vocabulary;

import org.apache.jena.ontapi.OntModelFactory;
import org.apache.jena.ontapi.OntSpecification;
import org.apache.jena.ontapi.model.OntModel;
import org.apache.jena.rdf.model.Property;

import org.apache.jena.rdf.model.Resource;

/**
 * PROV vocabulary.
 * 
 * @author Martynas Jusevičius {@literal <martynas@atomgraph.com>}
 */
public class PROV {

    static
    {
        org.apache.jena.sys.JenaSystem.init(); // ensure Jena (RDFS vocab) is initialized before ontapi touches it
    }
    
    /** The RDF model that holds the vocabulary terms */
    private static OntModel m_model = OntModelFactory.createModel(OntSpecification.OWL1_FULL_MEM);
    
    /** The namespace of the vocabulary as a string */
    public static final String NS = "http://www.w3.org/ns/prov#";
    
    /**
     * The namespace of the vocabulary as a string.
     * 
     * @return namespace URI
     * @see #NS
     */
    public static String getURI()
    {
        return NS;
    }
    
    /** The namespace of the vocabulary as a resource */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** Entity class */
    public static final Resource Entity = m_model.createOntClass( NS + "Entity" );

    /** Activity class */
    public static final Resource Activity = m_model.createOntClass( NS + "Activity" );

    /** Agent class */
    public static final Resource Agent = m_model.createOntClass( NS + "Agent" );

    /** Was attributed to property */
    public static final Property wasAttributedTo = m_model.createObjectProperty( NS + "wasAttributedTo" );

    /** Was derived from property */
    public static final Property wasDerivedFrom = m_model.createObjectProperty( NS + "wasDerivedFrom" );

    /** Was generated by property */
    public static final Property wasGeneratedBy = m_model.createObjectProperty( NS + "wasGeneratedBy" );

    /** Was started by property */
    public static final Property wasStartedBy = m_model.createObjectProperty( NS + "wasStartedBy" );

    /** Started at time property */
    public static final Property startedAtTime = m_model.createDataProperty( NS + "startedAtTime" );

    /** Ended at time property */
    public static final Property endedAtTime = m_model.createDataProperty( NS + "endedAtTime" );
    
    /** Generated at time property */
    public static final Property generatedAtTime = m_model.createDataProperty( NS + "generatedAtTime" );

}
