<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
xmlns="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:ixsl="http://saxonica.com/ns/interactiveXSLT"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:rdfae="https://w3id.org/atomgraph/rdfa-editor#"
extension-element-prefixes="ixsl"
xpath-default-namespace="http://www.w3.org/1999/xhtml"
version="3.0">

<!--
    RDFa editor entry point. The editor UI is fully generated by this stylesheet:
    drop it onto any host page with a #content container and author XHTML+RDFa -
    structured block editing plus right-click RDFa annotation.

    Modules:
    - RDFa2RDFXML-v3.xsl   RDFa 1.1 to RDF/XML extraction (pure XSLT, tested headless)
    - content-model.xsl    XHTML Strict content model as data (pure XSLT, include-free)
    - canonical-xhtml.xsl  canonical serialization form (pure XSLT, tested headless)
    - vocab.xsl            generic ontology RDF/XML to term maps
    - overlay.xsl          annotation form: rendering, reading, populating, visibility
    - typeahead.xsl        autocomplete lookups for the property and type fields
    - annotate.xsl         right-click dispatch, apply/remove annotation, extraction modal
    - edit.xsl             XHTML editing: blocks, keyboard, toolbar, dialogs, drag-and-drop
    - blocks.xsl           object blocks: island predicate, render hook, extension points
    - tables.xsl           table blocks: insert dialog, row/column operations, cell traversal
    - select.xsl           region-scoped select-all and cross-host selection delete
    - input.xsl            input triggers: slash menu and markdown shorthands
-->

    <xsl:include href="RDFa2RDFXML-v3.xsl"/>
    <xsl:include href="group-sort-triples.xsl"/>
    <xsl:include href="content-model.xsl"/>
    <xsl:include href="canonical-xhtml.xsl"/>
    <xsl:include href="lint-rdfa.xsl"/>
    <xsl:include href="lint-xhtml.xsl"/>
    <xsl:include href="vocab.xsl"/>
    <xsl:include href="overlay.xsl"/>
    <xsl:include href="typeahead.xsl"/>
    <xsl:include href="annotate.xsl"/>
    <xsl:include href="edit.xsl"/>
    <xsl:include href="blocks.xsl"/>
    <xsl:include href="tables.xsl"/>
    <xsl:include href="select.xsl"/>
    <xsl:include href="input.xsl"/>
    <xsl:include href="undo.xsl"/>
    <xsl:include href="navigate.xsl"/>

    <!-- the initial template (SaxonJS.transform initialTemplate in the host page).
         Everything here is synchronous: the host page preloads the vocabulary
         documents into the SaxonJS document pool (SaxonJS.getResource +
         documentPool), keyed by page-relative URI -->
    <xsl:template name="rdfae:main">
        <xsl:call-template name="rdfae:init-state"/>
        <xsl:call-template name="rdfae:init-editor"/>
    </xsl:template>

    <!-- all editor state lives on a single window.rdfaEditor container (mirrors
         LinkedDataHub's window.LinkedDataHub); reached everywhere via rdfae:editor-state().
         Hosts with their own initial template call this from there instead of main -->
    <xsl:template name="rdfae:init-state">
        <xsl:variable name="state" select="ixsl:call(ixsl:window(), 'Object', [])"/>
        <ixsl:set-property name="rdfaEditor" select="$state" object="ixsl:window()"/>
        <xsl:for-each select="('editingSpan', 'range', 'activeBlock', 'draggedBlock',
                'editRange', 'editingLink', 'insertHost', 'lastUndoHost',
                'breadcrumbLeaf', 'draggedSectionHeading', 'findNode', 'tocRoot',
                'slashHost', 'sweepAnchorNode', 'sweepAnchorHost', 'sweepRegion')">
            <ixsl:set-property name="{.}" select="()" object="$state"/>
        </xsl:for-each>
        <ixsl:set-property name="lastUndoTime" select="0" object="$state"/>
        <ixsl:set-property name="findOffset" select="1" object="$state"/>
        <ixsl:set-property name="sweepAnchorOffset" select="0" object="$state"/>
    </xsl:template>

    <!-- the full editor bring-up: page chrome (undo stash, overlay, output modal,
         toolbar, dialogs, drawers) plus block init of every editable region. Hosts
         that render regions lazily call this once, when the first region appears -->
    <xsl:template name="rdfae:init-editor">
        <xsl:call-template name="rdfae:init-undo"/>
        <xsl:call-template name="rdfae:init-overlay"/>
        <xsl:call-template name="rdfae:init-annotate"/>
        <xsl:call-template name="rdfae:init-editing"/>
        <xsl:call-template name="rdfae:init-navigate"/>
    </xsl:template>

    <!-- the single window.rdfaEditor container that holds all mutable editor state;
         every read/write of that state goes through this accessor -->
    <xsl:function name="rdfae:editor-state">
        <xsl:sequence select="ixsl:get(ixsl:window(), 'rdfaEditor')"/>
    </xsl:function>

</xsl:stylesheet>
