PREFIX dct:        <http://purl.org/dc/terms/>
PREFIX xsd:        <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf:        <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dh:         <https://www.w3.org/ns/ldt/document-hierarchy#>
PREFIX sioc:       <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
    ?item a dh:Item ;
        sioc:has_container ?this ;
        dh:slug ?id ;
        dct:title ?string ;
        rdf:value ?integer
}
WHERE
{
    ?row <#id> ?id ;
        <#string> ?string ;
        <#integer> ?integer_string .

    BIND(uri(concat(str(?this), encode_for_uri(?id), "/")) AS ?item)
    BIND(xsd:integer(?integer_string) AS ?integer)

    OPTIONAL 
    { ?row <#optional> ?optional }
}