PREFIX  pidc: <http://permid.org/ontology/common/>
PREFIX  pidf: <http://permid.org/ontology/financial/>
PREFIX  sioc: <http://rdfs.org/sioc/ns#>

CONSTRUCT 
  { 
    ?this ?p ?o .
    ?instrument sioc:has_container <instruments/> .
    ?instrument ?instrumentP ?instrumentO .
  }
WHERE
  {   { GRAPH ?graph
          { ?this  ?p  ?o }
      }
    UNION
      { { SELECT  ?instrument # Container queries need a sub-SELECT
          WHERE
            { ?instrument  a                  pidf:Instrument ;
                        pidc:hasPermId        ?hasPermId ;
                        pidc:hasName          ?hasName ;
                        pidf:isIssuedBy       ?isIssuedBy
              OPTIONAL
                { ?instrument  pidf:hasPrimaryQuote  ?hasPrimaryQuote }
              OPTIONAL
                { ?instrument  pidf:hasInstrumentStatus  ?hasInstrumentStatus }
              OPTIONAL
                { ?instrument  pidf:hasAssetClass  ?hasAssetClass }
            }
        }
        ?instrument  ?instrumentP  ?instrumentO
      }
  }